#pragma once

#include <Windows.h>
#include <fltUser.h>
#include <WinTrust.h>
#include <Softpub.h>
#include <winver.h>
#include <TraceLoggingProvider.h>
#include <winmeta.h>
#include <ShlObj.h>
#include <userenv.h>
#include <WtsApi32.h>
#include <TlHelp32.h>
// #include <wincrypt.h>

#include <time.h>
#include <stdlib.h>
#include <thread>
#include <string>
#include <vector>
#include <mutex>
#include <iostream>
#include <fstream>
#include <filesystem>


typedef struct _DECOYMON_SEND_MESSAGE_INFORMATION {
	DWORD operationType;
	ULONG_PTR pid;
	WCHAR path[260];
} DECOYMON_SEND_MESSAGE_INFORMATION, * PDECOYMON_SEND_MESSAGE_INFORMATION;

typedef struct _DECOYMON_SEND_MESSAGE_STRUCT {
	FILTER_MESSAGE_HEADER header;
	DECOYMON_SEND_MESSAGE_INFORMATION info;
} DECOYMON_SEND_MESSAGE_STRUCT, * PDECOYMON_SEND_MESSAGE_STRUCT;

typedef struct _DECOYMON_REPLY_MESSAGE_INFORMATION {
	BOOLEAN isPIDRejected;
} DECOYMON_REPLY_MESSAGE_INFORMATION, * PDECOYMON_REPLY_MESSAGE_INFORMATION;

typedef struct _DECOYMON_REPLY_MESSAGE_STRUCT {
	FILTER_REPLY_HEADER header;
	DECOYMON_REPLY_MESSAGE_INFORMATION info;
} DECOYMON_REPLY_MESSAGE_STRUCT, * PDECOYMON_REPLY_MESSAGE_STRUCT;

enum OPERATION_TYPE {
	DECOY_DELETED = 0x1,
	DECOY_RENAMED = 0x2,
	DECOY_COPIED = 0x4,
	DECOY_READ = 0x8,
	DECOY_MEMORYMAPPED = 0x10,
	DECOY_DIR_DELETED = 0x20,
	DECOY_DIR_RENAMED = 0x40,
	DECOY_DIR_ADD = 0x1000
};


constexpr auto SERVICE_IDENTIFIER = L"RANskril CORE";
constexpr auto SERVICE_SUBIDENTIFIER_INIT = L"INITIALIZER";
constexpr auto SERVICE_SUBIDENTIFIER_END = L"UNINITIALIZER";
constexpr auto REGISTRY_COMPONENT_SUBIDENTIFIER = L"REGISTRY HANDLER";
constexpr auto KERNELCOMM_COMPONENT_SUBIDENTIFIER = L"KERNEL COMMUNICATOR";
constexpr auto DIRECTORY_SUBIDENTIFIER = L"DIRECTORY HANDLER";
constexpr auto DECOY_SUBIDENTIFIER = L"DECOY HANDLER";
constexpr auto TRIUNEJDG_SUBIDENTIFIER = L"TRIUNEJDG SYSTEM";
constexpr auto TRIUNEJDG_AMSI_SUBIDENTIFIER = L"TRIUNEJDG-AMSI";
constexpr auto TRIUNEJDG_WVT_SUBIDENTIFIER = L"TRIUNEJDG-WVT";
constexpr auto TRIUNEJDG_ETW_SUBIDENTIFIER = L"TRIUNEJDG-ETW";
constexpr auto UTILS_SUBIDENTIFIER = L"UTILS-MISCELLANOUS";

constexpr auto SWITCH_SUBIDENTIFIER_MAIN = L"FILTER MESSAGE LISTENER";	
constexpr auto SWITCH_SUBIDENTIFIER_NOTIFIER = L"VERDICT NOTIFIER THREAD";	
constexpr auto SWITCH_SUBIDENTIFIER_RECEIVER = L"COMMAND RECEIVER THREAD";
constexpr auto SWITCH_SUBIDENTIFIER_STATUSPING = L"STATUS PING DUPLEX THREAD";