#pragma once

#define DEVICE_DECOYMON 0x8193

#define IOCTL_ADD_DECOY_FILE CTL_CODE(DEVICE_DECOYMON, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_REMOVE_DECOY_FILE CTL_CODE(DEVICE_DECOYMON, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ADD_DECOY_DIRECTORY CTL_CODE(DEVICE_DECOYMON, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_REMOVE_DECOY_DIRECTORY CTL_CODE(DEVICE_DECOYMON, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ADD_EXCLUDED_DIRECTORY CTL_CODE(DEVICE_DECOYMON, 0x804, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_RANSKRILOVERRIDE_TURNOFF CTL_CODE(DEVICE_DECOYMON, 0x805, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_RANSKRILOVERRIDE_TURNON CTL_CODE(DEVICE_DECOYMON, 0x806, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_EMPTY_DECOY_FILE_MEMORY CTL_CODE(DEVICE_DECOYMON, 0x807, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_EMPTY_DECOY_DIRECTORY_MEMORY CTL_CODE(DEVICE_DECOYMON, 0x808, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_EMPTY_EXCLUDED_DIRECTORY_MEMORY CTL_CODE(DEVICE_DECOYMON, 0x809, METHOD_BUFFERED, FILE_ANY_ACCESS)